defaults:
  - dataset: justRAIGS
  - model: diffusion
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .

seed: 7
project_name: "Glaucoma Counterfactual DIffusion"


