const:
  v2: torchvision.transforms.v2

defaults:
  - data: justRAIGS
  - model: diffusion
  - inference: orig
  - training: train
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  output_subdir: null
  run:
    dir: .

seed: 7
project_name: "Glaucoma Counterfactual Diffusion"
# options in ModeEnum
# mode: ${mode:TRAIN}


